name: Project CICD

'on':
 push:
 pull_request:
   branches:
     - main
 
jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
    - name: Step-1 Checkout-respository to ubuntu runner
      uses: actions/checkout@v3

    - name: Step-2 install Nodes.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.0

    - name: Step-3 Install dependies
      run: npm ci


